version: '3.9'
name: "todo"

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - ../config/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB" ]
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      todo-network:

  migrations:
    build:
      context: ./..
      dockerfile: deployment/migration/Dockerfile
    env_file:
      - ../config/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      todo-network:

  app:
    ports:
      - "8080:8080"
    env_file:
      - ../config/.env
    build:
      context: ./..
      dockerfile: deployment/app/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    logging:
      driver: "json-file"
      options:
        max-size: "2G"
        max-file: "1"
    networks:
      todo-network:

volumes:
  postgres:
    driver: local

networks:
  todo-network:
    name: todo-network
