basePath: /api/v1/
definitions:
  service.CreateStatusParams:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  service.CreateStatusResponse:
    properties:
      id:
        type: integer
    type: object
  v1.response:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    name: API [Roman] Support
  description: Swagger API for Golang Project TODO.
  license:
    name: romandnk
    url: https://github.com/romandnk/todo
  termsOfService: http://swagger.io/terms/
  title: TODO App Swagger
  version: "1.0"
paths:
  /statuses/:
    post:
      description: Create new task status.
      parameters:
      - description: required JSON body with status name
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.CreateStatusParams'
      responses:
        "200":
          description: Status was created successfully
          schema:
            $ref: '#/definitions/service.CreateStatusResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/v1.response'
      summary: CreateStatus
      tags:
      - Statuses
swagger: "2.0"
